%% The properties defined for each character in Pottinator %%

prop(lily_potter, gender, is_female).
prop(lily_potter, bloodness, is_muggle_born).
prop(lily_potter, house, is_in_house_gryffindor).
prop(lily_potter, hair_colour, has_auburn_hair).
prop(lily_potter, species, is_human).
prop(lily_potter, status, is_dead).
prop(lily_potter, had_other_forms, had_no_other_forms).
prop(lily_potter, had_played_on_quidditch_team, had_not_played_on_quidditch_team).
prop(lily_potter, movie_first_appearance, first_appeared_in_harry_potter_and_the_philosophers_stone).
prop(james_potter, gender, is_male).
prop(james_potter, bloodness, is_pure_blood).
prop(james_potter, house, is_in_house_gryffindor).
prop(james_potter, hair_colour, has_black_hair).
prop(james_potter, species, is_human).
prop(james_potter, status, is_dead).
prop(james_potter, had_other_forms, had_another_form).
prop(james_potter, had_played_on_quidditch_team, had_played_on_quidditch_team).
prop(james_potter, movie_first_appearance, first_appeared_in_harry_potter_and_the_philosophers_stone).
prop(severus_snape, gender, is_male).
prop(severus_snape, bloodness, is_half_blood).
prop(severus_snape, house, is_in_house_slytherin).
prop(severus_snape, hair_colour, has_black_hair).
prop(severus_snape, species, is_human).
prop(severus_snape, status, is_dead).
prop(severus_snape, had_other_forms, had_no_other_forms).
prop(severus_snape, had_played_on_quidditch_team, had_not_played_on_quidditch_team).
prop(severus_snape, movie_first_appearance, first_appeared_in_harry_potter_and_the_philosophers_stone).
prop(tom_riddle, gender, is_male).
prop(tom_riddle, bloodness, is_half_blood).
prop(tom_riddle, house, is_in_house_slytherin).
prop(tom_riddle, hair_colour, is_bald_headed).
prop(tom_riddle, species, is_human).
prop(tom_riddle, status, is_dead).
prop(tom_riddle, had_other_forms, had_another_form).
prop(tom_riddle, had_played_on_quidditch_team, had_not_played_on_quidditch_team).
prop(tom_riddle, movie_first_appearance, first_appeared_in_harry_potter_and_the_philosophers_stone).
prop(dobby, gender, is_male).
prop(dobby, bloodness, is_a_creature).
prop(dobby, house, is_in_no_house).
prop(dobby, hair_colour, is_bald_headed).
prop(dobby, species, is_a_house_elf).
prop(dobby, status, is_dead).
prop(dobby, had_other_forms, had_no_other_forms).
prop(dobby, had_played_on_quidditch_team, had_not_played_on_quidditch_team).
prop(dobby, movie_first_appearance, first_appeared_in_harry_potter_and_the_chamber_of_secrets).
prop(sirius_black, gender, is_male).
prop(sirius_black, bloodness, is_pure_blood).
prop(sirius_black, house, is_in_house_gryffindor).
prop(sirius_black, hair_colour, has_black_hair).
prop(sirius_black, species, is_human).
prop(sirius_black, status, is_dead).
prop(sirius_black, had_other_forms, had_another_form).
prop(sirius_black, had_played_on_quidditch_team, had_not_played_on_quidditch_team).
prop(sirius_black, movie_first_appearance, first_appeared_in_harry_potter_and_the_prisoner_of_azkaban).
prop(harry_potter, gender, is_male).
prop(harry_potter, bloodness, is_half_blood).
prop(harry_potter, house, is_in_house_gryffindor).
prop(harry_potter, hair_colour, has_black_hair).
prop(harry_potter, species, is_human).
prop(harry_potter, status, is_still_alive).
prop(harry_potter, had_other_forms, had_no_other_forms).
prop(harry_potter, had_played_on_quidditch_team, had_played_on_quidditch_team).
prop(harry_potter, movie_first_appearance, first_appeared_in_harry_potter_and_the_philosophers_stone).
prop(ron_weasley, gender, is_male).
prop(ron_weasley, bloodness, is_pure_blood).
prop(ron_weasley, house, is_in_house_gryffindor).
prop(ron_weasley, hair_colour, has_red_hair).
prop(ron_weasley, species, is_human).
prop(ron_weasley, status, is_still_alive).
prop(ron_weasley, had_other_forms, had_no_other_forms).
prop(ron_weasley, had_played_on_quidditch_team, had_played_on_quidditch_team).
prop(ron_weasley, movie_first_appearance, first_appeared_in_harry_potter_and_the_philosophers_stone).
prop(hermione_granger, gender, is_female).
prop(hermione_granger, bloodness, is_muggle_born).
prop(hermione_granger, house, is_in_house_gryffindor).
prop(hermione_granger, hair_colour, has_brown_hair).
prop(hermione_granger, species, is_human).
prop(hermione_granger, status, is_still_alive).
prop(hermione_granger, had_other_forms, had_no_other_forms).
prop(hermione_granger, had_played_on_quidditch_team, had_not_played_on_quidditch_team).
prop(hermione_granger, movie_first_appearance, first_appeared_in_harry_potter_and_the_philosophers_stone).
prop(lucius_malfoy, gender, is_male).
prop(lucius_malfoy, bloodness, is_pure_blood).
prop(lucius_malfoy, house, is_in_house_slytherin).
prop(lucius_malfoy, hair_colour, has_blonde_hair).
prop(lucius_malfoy, species, is_human).
prop(lucius_malfoy, status, is_still_alive).
prop(lucius_malfoy, had_other_forms, had_no_other_forms).
prop(lucius_malfoy, had_played_on_quidditch_team, had_not_played_on_quidditch_team).
prop(lucius_malfoy, movie_first_appearance, first_appeared_in_harry_potter_and_the_chamber_of_secrets).